### ISSUE TITLE
pre-commit hooks should not set verbose: true

### ISSUE THREAD

**Issue by asottile** [thg-consulting/it#25]
this is a debugging flag, I'm temporarily removing this from pre-commit.com for now, please fix this and revert this change:  https://github.com/pre-commit/pre-commit.com/commit/1bcb29c6a3fc5cff707c79d06fbbc87c5dc900f2

**Comment by asottile** [comment]
CC @isidentical

**Comment by isidentical** [comment]
Should be fixed, won't want to deal with any other mess. Thanks for notifying!
