### ISSUE TITLE
What is the license of the tool?

### ISSUE THREAD

**Issue by mre** [thg-consulting/it#27]
Hey, I'm adding IT to [analysis-tools.dev](https://analysis-tools.dev/) over here: https://github.com/analysis-tools-dev/static-analysis/pull/553
One thing I noticed was that I can't find any license information for InspectorTiger anywhere. 🤔 
By definition that means the tool is proprietary and I'm not sure if that is your intention or it was just an oversight.
Maybe you can shed some light on the situation. 😊

**Comment by isidentical** [comment]
Indeed, thanks for noticing that. I've licensed it with MIT from the commit 0a32be5a6112dde0943cd8f4063a49c0e96a85c2.

**Comment by mre** [comment]
Thanks!
